### ISSUE TITLE
`get_object` has required session parameter but other methods hasn't session parameter. Why for?

### ISSUE THREAD

**Issue by tulinev** [hlf20010508/miniopy-async#23]
# `get_object` has required `session` parameter but other methods hasn't `session` parameter

## Describe the bug

If external session is useful in some use cases, it could be optional argument. But if it's so, all other methods have to have same `session` parameter.

**Comment by hlf20010508** [comment]
Because `get_object` can be used alone.
If you don't provide a session, it will create a session inside `get_object`, but once `get_object` returns, the session closes, so that you can't get full content from the response.
That's why I set param `session` to `required`.
And `get_object` is only used by `fget_object`, it will pass its session to `get_object`, so it doesn't have such problem.

**Comment by hlf20010508** [comment]
This was discussed [here](https://github.com/hlf20010508/miniopy-async/pull/15#issuecomment-1538445349).
I forgot to update the examples and docs of `get_object`.

**Comment by hlf20010508** [comment]
Other methods don't have this problem.
Outside session is needed only for downloading content, because users can manually `read`, no one knows when they `read`, when close the session.
